import type PptxGenJS from 'pptxgenjs'
import type { ParsedStep, Terminology } from '@/types'
import { EXCEL_MAPPINGS } from '@/lib/parser/excelMappings'
import { stripHTML } from '@/lib/security/sanitize'

const DUKE = '003087'
const WHITE = 'FFFFFF'
const GRAY = '64748B'
const LIGHT_BG = 'F1F5F9'

function getToolName(step: ParsedStep, terminology: Terminology) {
  return terminology === 'excel' ? EXCEL_MAPPINGS[step.toolKey].tool : step.alteryxTool
}

function getToolDetail(step: ParsedStep, terminology: Terminology) {
  return terminology === 'excel' ? EXCEL_MAPPINGS[step.toolKey].detail : step.alteryxDetail
}

export async function exportToPptx(steps: ParsedStep[], terminology: Terminology) {
  const PptxGenJS = (await import('pptxgenjs')).default
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_WIDE'
  pptx.author = 'Ophi by JAKT.AI'
  pptx.title = 'Code Translation Report'

  const termLabel = terminology === 'excel' ? 'Excel' : 'Alteryx'

  // --- Slide 1: Title ---
  const titleSlide = pptx.addSlide()
  titleSlide.background = { color: DUKE }
  titleSlide.addText('Ophi', {
    x: 0.8, y: 1.0, w: 11, h: 1,
    fontSize: 48, fontFace: 'Arial', bold: true, color: WHITE,
  })
  titleSlide.addText(`Python to ${termLabel} Translation`, {
    x: 0.8, y: 2.0, w: 11, h: 0.6,
    fontSize: 24, fontFace: 'Arial', color: WHITE,
  })
  titleSlide.addText(`${steps.length} transformation steps detected`, {
    x: 0.8, y: 3.0, w: 11, h: 0.5,
    fontSize: 14, fontFace: 'Arial', color: WHITE, italic: true,
  })
  titleSlide.addText('Generated by Ophi — JAKT.AI', {
    x: 0.8, y: 6.5, w: 11, h: 0.4,
    fontSize: 10, fontFace: 'Arial', color: WHITE,
  })

  // --- Slide 2: Workflow Overview ---
  const overviewSlide = pptx.addSlide()
  overviewSlide.addText('Workflow Overview', {
    x: 0.5, y: 0.3, w: 12, h: 0.6,
    fontSize: 24, fontFace: 'Arial', bold: true, color: DUKE,
  })

  const tableRows: PptxGenJS.TableRow[] = [
    [
      { text: '#', options: { bold: true, color: WHITE, fill: { color: DUKE }, fontSize: 10, align: 'center' } },
      { text: 'Python Code', options: { bold: true, color: WHITE, fill: { color: DUKE }, fontSize: 10 } },
      { text: '', options: { fill: { color: DUKE } } },
      { text: `${termLabel} Equivalent`, options: { bold: true, color: WHITE, fill: { color: DUKE }, fontSize: 10 } },
    ],
  ]

  steps.forEach((step, i) => {
    const toolName = getToolName(step, terminology)
    tableRows.push([
      { text: String(i + 1), options: { fontSize: 9, align: 'center', fill: { color: i % 2 === 0 ? LIGHT_BG : WHITE } } },
      { text: step.code.length > 50 ? step.code.substring(0, 50) + '...' : step.code, options: { fontSize: 9, fontFace: 'Courier New', fill: { color: i % 2 === 0 ? LIGHT_BG : WHITE } } },
      { text: '\u2192', options: { fontSize: 9, align: 'center', fill: { color: i % 2 === 0 ? LIGHT_BG : WHITE } } },
      { text: toolName, options: { fontSize: 9, bold: true, color: step.color.replace('#', ''), fill: { color: i % 2 === 0 ? LIGHT_BG : WHITE } } },
    ])
  })

  overviewSlide.addTable(tableRows, {
    x: 0.5, y: 1.1, w: 12,
    colW: [0.5, 5, 0.5, 6],
    border: { type: 'solid', pt: 0.5, color: 'CBD5E1' },
    autoPage: true,
    autoPageRepeatHeader: true,
  })

  // --- Slides 3+: One per step ---
  steps.forEach((step, i) => {
    const slide = pptx.addSlide()
    const toolName = getToolName(step, terminology)
    const toolDetail = getToolDetail(step, terminology)
    const colorHex = step.color.replace('#', '')

    // Top accent bar
    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: 13.33, h: 0.08, fill: { color: colorHex },
    })

    // Step badge
    slide.addText(`STEP ${i + 1}`, {
      x: 0.5, y: 0.3, w: 1.2, h: 0.35,
      fontSize: 10, fontFace: 'Arial', bold: true, color: WHITE,
      fill: { color: colorHex }, align: 'center',
    })

    // Category tag
    slide.addText(step.cat.toUpperCase(), {
      x: 1.85, y: 0.3, w: 1.2, h: 0.35,
      fontSize: 9, fontFace: 'Arial', bold: true, color: GRAY,
    })

    // Tool name headline
    slide.addText(step.tool, {
      x: 0.5, y: 0.85, w: 12, h: 0.6,
      fontSize: 28, fontFace: 'Arial', bold: true, color: '1e293b',
    })

    // Explanation
    slide.addText(stripHTML(step.explain), {
      x: 0.5, y: 1.5, w: 12, h: 0.8,
      fontSize: 13, fontFace: 'Arial', color: GRAY,
    })

    // Equivalent section
    slide.addText(`${termLabel} EQUIVALENT`, {
      x: 0.5, y: 2.6, w: 12, h: 0.3,
      fontSize: 9, fontFace: 'Arial', bold: true, color: GRAY,
    })
    slide.addText(toolName, {
      x: 0.5, y: 2.9, w: 5, h: 0.4,
      fontSize: 16, fontFace: 'Arial', bold: true, color: colorHex,
    })
    slide.addText(toolDetail, {
      x: 0.5, y: 3.35, w: 12, h: 0.5,
      fontSize: 11, fontFace: 'Arial', color: GRAY,
    })

    // Source code section
    slide.addText('SOURCE CODE', {
      x: 0.5, y: 4.2, w: 12, h: 0.3,
      fontSize: 9, fontFace: 'Arial', bold: true, color: GRAY,
    })
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.5, y: 4.55, w: 12, h: 1.2, fill: { color: LIGHT_BG },
    })
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.5, y: 4.55, w: 0.06, h: 1.2, fill: { color: DUKE },
    })
    slide.addText(step.code, {
      x: 0.75, y: 4.65, w: 11.5, h: 1,
      fontSize: 12, fontFace: 'Courier New', color: DUKE,
    })

    // Footer
    slide.addText(`Line ${step.line}`, {
      x: 0.5, y: 7, w: 3, h: 0.3,
      fontSize: 9, fontFace: 'Arial', color: GRAY,
    })
  })

  pptx.writeFile({ fileName: `ophi-translation-${termLabel.toLowerCase()}.pptx` })
}
